[build]
command = "./gradlew :site:kobwebExport --stacktrace --info"
publish = "site/build/dist"

[context.production.environment]
GRADLE_HOME = "/opt/gradle"  # If necessary for the build

[build.environment]
JAVA_VERSION = "17"
